seed_everything: 42

model:
  vocab_size: 1024
  context_length: 128
  dim: 256
  depth: 6
  heads: 8
  dim_head: 32
  ffn_dim: 1024
  dropout: 0.1
  embedding_dropout: 0.1
  attention_norm_layer: "LayerNorm"
  attention_activation_layer: "GELU"
  attention_linear_layer: "Linear"
  feedforward_norm_layer: "LayerNorm"
  feedforward_activation_layer: "GELU"
  feedforward_linear_layer: "Linear"

trainer:
  max_epochs: 50
  accelerator: auto
  devices: 1
  precision: 16
  num_sanity_val_steps: 0
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: gpt-shakespeare
      name: gpt-small
      save_dir: ./wandb_logs
      log_model: false

data:
  dataset_name: shakespeare
  data_dir: ./data/shakespeare
  context_length: 128
  batch_size: 32
  num_workers: 6
  tokenizer_name: bpe
  vocab_size: 1024
  
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0003
    weight_decay: 0.0001

lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 20
    gamma: 0.5