seed_everything: 42

model:
  image_size: 32
  patch_size: 4
  dim: 256
  depth: 6
  heads: 8
  dim_head: 64
  channels: 3
  dropout: 0.1
  embedding_dropout: 0.1
  num_classes: 10
  attention_norm_layer: "LayerNorm"
  attention_activation_layer: "GELU"
  attention_linear_layer: "Linear"
  feedforward_norm_layer: "LayerNorm"
  feedforward_activation_layer: "GELU"
  feedforward_linear_layer: "Linear"
  ffn_dim: 1024

trainer:
  max_epochs: 50
  accelerator: auto
  devices: 1
  precision: 16
  limit_train_batches: 10
  limit_val_batches: 10
  num_sanity_val_steps: 0
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: vit-cifar10
      name: vit-small
      save_dir: ./wandb_logs
      log_model: false

data:
  dataset_name: cifar10
  data_dir: ./data/
  batch_size: 128
  num_workers: 4
  image_size: 32

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0003
    weight_decay: 0.0001

lr_scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 20
    gamma: 0.5